/*
  Warnings:

  - You are about to drop the `Post` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `User` table. If the table is not empty, all the data it contains will be lost.

*/
-- CreateEnum
CREATE TYPE "AddressType" AS ENUM ('PERMANENT', 'PRESENT');

-- CreateEnum
CREATE TYPE "Division" AS ENUM ('DHAKA', 'CHITTAGONG', 'RAJSHAHI', 'KHULNA', 'BARISAL', 'SYLHET', 'RANGPUR', 'MYMENSINGH');

-- CreateEnum
CREATE TYPE "District" AS ENUM ('DHAKA', 'FARIDPUR', 'GAZIPUR', 'GOPALGANJ', 'KISHOREGANJ', 'MADARIPUR', 'MANIKGANJ', 'MUNSHIGANJ', 'NARAYANGANJ', 'NARSINGDI', 'RAJBARI', 'SHARIATPUR', 'TANGAIL', 'CHITTAGONG', 'BANDARBAN', 'BRAHMANBARIA', 'CHANDPUR', 'COMILLA', 'COXSBAZAR', 'FENI', 'KHAGRACHHARI', 'LAKSHMIPUR', 'NOAKHALI', 'RANGAMATI', 'RAJSHAHI', 'BOGURA', 'JOYPURHAT', 'NAOGAON', 'NATORE', 'CHAPAINAWABGANJ', 'PABNA', 'SIRAJGANJ', 'KHULNA', 'BAGERHAT', 'CHUADANGA', 'JASHORE', 'JHENAIDAH', 'KUSHTIA', 'MAGURA', 'MEHERPUR', 'NARAIL', 'SATKHIRA', 'BARISHAL', 'BARGUNA', 'BHOLA', 'JHALOKATHI', 'PATUAKHALI', 'PIROJPUR', 'SYLHET', 'HABIGANJ', 'MOULVIBAZAR', 'SUNAMGANJ', 'RANGPUR', 'DINAJPUR', 'GAIBANDHA', 'KURIGRAM', 'LALMONIRHAT', 'NILPHAMARI', 'PANCHAGARH', 'THAKURGAON', 'MYMENSINGH', 'JAMALPUR', 'NETROKONA', 'SHERPUR');

-- CreateEnum
CREATE TYPE "Upazila" AS ENUM ('DHAMRAI', 'DOHAR', 'KERANIGANJ', 'NAWABGANJ_DHAKA', 'SAVAR', 'TEJGAON', 'MOHAMMADPUR', 'KOTWALI_DHAKA', 'SUTRAPUR', 'MOTIJHEEL', 'RAMNA', 'GULSHAN', 'MIRPUR', 'PALLABI', 'CANTONMENT_DHAKA', 'UTTARA', 'KHILKHET', 'SABUJBAGH', 'DEMRA', 'JATRABARI', 'SHAHBAGH', 'LALBAGH', 'HAZARIBAGH', 'NEW_MARKET', 'DHANMONDI', 'TEJGAON_INDUSTRIAL', 'BADDA', 'KAFRUL', 'KAMRANGIRCHAR', 'KHILGAON', 'MUGDA', 'SHAH_ALI', 'TURAG', 'DAKSHINKHAN', 'UTTARKHAN', 'BIMANBANDAR', 'RUPNAGAR', 'VATARA', 'ADABOR', 'MOHAKHALI', 'RAMPURA', 'BANANI', 'FARIDPUR_SADAR', 'ALFADANGA', 'BOALMARI', 'SADARPUR_FARIDPUR', 'NAGARKANDA', 'BHANGA', 'CHARBHADRASAN', 'MADHUKHALI', 'SALTHA', 'GAZIPUR_SADAR', 'KALIAKAIR', 'KAPASIA', 'SREEPUR', 'KALIGANJ_GAZIPUR', 'GOPALGANJ_SADAR', 'KASHIANI', 'TUNGIPARA', 'KOTALIPARA', 'MUKSUDPUR', 'KISHOREGANJ_SADAR', 'ASTAGRAM', 'BAJITPUR', 'BHAIRAB', 'HOSSAINPUR', 'ITNA', 'KARIMGANJ_KISHOREGANJ', 'KATIADI', 'KULIARCHAR', 'MITHAMAIN', 'NIKLI', 'PAKUNDIA', 'TARAIL', 'MADARIPUR_SADAR', 'RAJOIR', 'KALKINI', 'SHIBCHAR', 'MANIKGANJ_SADAR', 'SINGAIR', 'SHIBALAYA', 'SATURIA', 'HARIRAMPUR', 'GHIOR', 'DAULATPUR_MANIKGANJ', 'MUNSHIGANJ_SADAR', 'SREENAGAR', 'SIRAJDIKHAN', 'LOUHAJANG', 'GAJARIA', 'TONGIBARI', 'NARAYANGANJ_SADAR', 'ARAIHAZAR', 'BANDAR_NARAYANGANJ', 'RUPGANJ', 'SONARGAON', 'NARSINGDI_SADAR', 'BELABO', 'MONOHARDI', 'PALASH', 'RAIPURA_NARSINGDI', 'SHIBPUR', 'RAJBARI_SADAR', 'GOALANDA', 'PANGSHA', 'BALIAKANDI', 'KALUKHALI_RAJBARI', 'SHARIATPUR_SADAR', 'NARIA', 'ZAJIRA', 'GOSAIRHAT', 'BHEDARGANJ', 'DAMUDYA', 'TANGAIL_SADAR', 'SAKHIPUR', 'BASAIL', 'MADHUPUR', 'GHATAIL', 'KALIHATI', 'NAGARPUR_TANGAIL', 'MIRZAPUR', 'GOPALPUR_TANGAIL', 'DELDUAR', 'BHUAPUR', 'DHANBARI', 'ANWARA', 'BANSHKHALI', 'BOALKHALI', 'CHANDANAISH', 'FATIKCHHARI', 'HATHAZARI', 'LOHAGARA_CHITTAGONG', 'MIRSHARAI', 'PATIYA', 'RANGUNIA', 'RAOZAN', 'SANDWIP', 'SATKANIA', 'SITAKUNDA', 'KARNAPHULI', 'BANDARBAN_SADAR', 'THANCHI', 'LAMA', 'NAIKHONGCHHARI', 'ALI_KADAM', 'ROWANGCHHARI', 'RUMA', 'BRAHMANBARIA_SADAR', 'KASBA', 'NASIRNAGAR', 'SARAIL', 'ASHUGANJ', 'AKHAURA', 'NABINAGAR_BRAHMANBARIA', 'BANCHARAMPUR', 'BIJOYNAGAR', 'CHANDPUR_SADAR', 'FARIDGANJ', 'HAIMCHAR', 'HAZIGANJ', 'KACHUA_CHANDPUR', 'MATLAB_DAKSHIN', 'MATLAB_UTTAR', 'SHAHRASTI', 'COMILLA_SADAR', 'BARURA', 'BRAHMANPARA', 'BURICHANG', 'CHANDINA', 'CHAUDDAGRAM', 'DAUDKANDI', 'DEBIDWAR', 'HOMNA', 'LAKSAM', 'MURADNAGAR', 'NANGALKOT', 'COMILLA_SADAR_DAKSHIN', 'MEGHNA', 'MONOHARGONJ', 'TITAS', 'LALMAI', 'COXSBAZAR_SADAR', 'CHAKARIA', 'KUTUBDIA', 'UKHIA', 'MOHESHKHALI', 'PEKUA', 'RAMU', 'TEKNAF', 'FENI_SADAR', 'CHAGALNAIYA', 'DAGANBHUIYAN', 'PARSHURAM', 'FULGAZI', 'SONAGAZI', 'KHAGRACHHARI_SADAR', 'DIGHINALA', 'PANCHARI', 'LAXMICHHARI', 'MOHALCHARI', 'MANIKCHARI', 'RAMGARH_KHAGRACHHARI', 'MATIRANGA', 'GUIMARA', 'LAKSHMIPUR_SADAR', 'RAIPUR_LAKSHMIPUR', 'RAMGANJ', 'RAMGATI', 'KOMOL_NAGAR', 'NOAKHALI_SADAR', 'BEGUMGANJ', 'CHATKHIL', 'COMPANIGANJ_NOAKHALI', 'HATIYA', 'SENBAGH', 'SONAIMURI', 'SUBARNACHAR', 'KABIRHAT', 'RANGAMATI_SADAR', 'KAPTAI', 'KAWKHALI_RANGAMATI', 'BAGHAICHHARI', 'BARKAL', 'LANGADU', 'RAJASTHALI', 'BELAICHHARI', 'JURAICHHARI', 'NANIARCHAR', 'RAJSHAHI_SADAR', 'BAGHA', 'BAGMARA', 'CHARGHAT', 'DURGAPUR_RAJSHAHI', 'GODAGARI', 'MOHANPUR', 'PABA', 'PUTHIA', 'TANORE', 'BOGURA_SADAR', 'ADAMDIGHI', 'DHUNAT', 'DHUPCHANCHIA', 'GABTALI', 'KAHALOO', 'NANDIGRAM', 'SARIAKANDI', 'SHAJAHANPUR', 'SHERPUR_BOGURA', 'SHIBGANJ_BOGURA', 'SONATALA', 'JOYPURHAT_SADAR', 'AKKELPUR', 'KALAI', 'KHETLAL', 'PANCHBIBI', 'NAOGAON_SADAR', 'ATRAI', 'BADALGACHHI', 'MANDA', 'DHAMOIRHAT', 'MOHADEVPUR', 'NIAMATPUR', 'PATNITALA', 'PORSHA', 'RANINAGAR', 'SAPAHAR', 'NATORE_SADAR', 'BAGATIPARA', 'BARAIGRAM', 'GURUDASPUR', 'LALPUR', 'SINGRA', 'NALDANGA', 'CHAPAINAWABGANJ_SADAR', 'BHOLAHAT', 'GOMASTAPUR', 'NACHOLE', 'SHIBGANJ_CHAPAINAWABGANJ', 'PABNA_SADAR', 'ATGHARIA', 'BERA', 'BHANGURA', 'CHATMOHAR', 'FARIDPUR_PABNA', 'ISHWARDI', 'SANTHIA', 'SUJANAGAR', 'SIRAJGANJ_SADAR', 'BELKUCHI', 'CHAUHALI', 'KAMARKHANDA', 'KAZIPUR', 'RAIGANJ', 'SHAHJADPUR', 'TARASH', 'ULLAHPARA', 'KHULNA_SADAR', 'BATIAGHATA', 'DACOPE', 'DUMURIA', 'DIGHALIA', 'KOYRA', 'PAIKGACHHA', 'PHULTALA', 'RUPSA', 'TEROKHADA', 'BAGERHAT_SADAR', 'CHITALMARI', 'FAKIRHAT', 'KACHUA_BAGERHAT', 'MOLLAHAT', 'MONGLA', 'MORRELGANJ', 'RAMPAL', 'SARANKHOLA', 'CHUADANGA_SADAR', 'ALAMDANGA', 'DAMURHUDA', 'JIBANNAGAR', 'JASHORE_SADAR', 'ABHAYNAGAR', 'BAGHERPARA', 'CHAUGACHHA', 'JHIKARGACHHA', 'KESHABPUR', 'MANIRAMPUR', 'SHARSHA', 'JHENAIDAH_SADAR', 'HARINAKUNDA', 'KALIGANJ_JHENAIDAH', 'KOTCHANDPUR', 'MAHESHPUR', 'SHAILKUPA', 'KUSHTIA_SADAR', 'BHERAMARA', 'DAULATPUR_KUSHTIA', 'KHOKSA', 'KUMARKHALI', 'MIRPUR_KUSHTIA', 'MAGURA_SADAR', 'MOHAMMADPUR_MAGURA', 'SHALIKHA', 'SREEPUR_MAGURA', 'MEHERPUR_SADAR', 'GANGNI', 'MUJIBNAGAR', 'NARAIL_SADAR', 'KALIA', 'LOHAGARA_NARAIL', 'SATKHIRA_SADAR', 'ASSASUNI', 'DEBHATA', 'KALAROA', 'KALIGANJ_SATKHIRA', 'SHYAMNAGAR', 'TALA', 'BARISHAL_SADAR', 'AGAILJHARA', 'BABUGANJ', 'BAKERGANJ', 'BANARIPARA', 'GAURNADI', 'HIZLA', 'MEHENDIGANJ', 'MULADI', 'WAZIRPUR', 'BARGUNA_SADAR', 'AMTALI', 'BAMNA', 'BETAGI', 'PATHARGHATA', 'TALTALI', 'BHOLA_SADAR', 'BURHANUDDIN', 'CHAR_FASSON', 'DAULATKHAN', 'LALMOHAN', 'MANPURA', 'TAZUMUDDIN', 'JHALOKATHI_SADAR', 'KATHALIA', 'NALCHITY', 'RAJAPUR', 'PATUAKHALI_SADAR', 'BAUPHAL', 'DASHMINA', 'DUMKI', 'GALACHIPA', 'KALAPARA', 'MIRZAGANJ', 'RANGABALI', 'PIROJPUR_SADAR', 'BHANDARIA', 'KAWKHALI_PIROJPUR', 'MATHBARIA', 'NAZIRPUR', 'NESARABAD', 'INDURKANI', 'SYLHET_SADAR', 'BALAGANJ', 'BEANIBAZAR', 'BISHWANATH', 'COMPANIGANJ_SYLHET', 'FENCHUGANJ', 'GOLAPGANJ', 'GOWAINGHAT', 'JAINTIAPUR', 'KANAIGHAT', 'ZAKIGANJ', 'DAKSHIN_SURMA', 'OSMANI_NAGAR', 'HABIGANJ_SADAR', 'AJMIRIGANJ', 'BAHUBAL', 'BANIYACHONG', 'CHUNARUGHAT', 'LAKHAI', 'MADHABPUR', 'NABIGANJ_HABIGANJ', 'SAYESTAGANJ', 'MOULVIBAZAR_SADAR', 'BARLEKHA', 'JURI', 'KAMALGANJ', 'KULAURA', 'RAJNAGAR', 'SREEMANGAL', 'SUNAMGANJ_SADAR', 'BISHWAMVARPUR', 'CHHATAK', 'DERAI', 'DHARAMAPASHA', 'DOWARABAZAR', 'JAGANNATHPUR', 'JAMALGANJ', 'SHALLA', 'TAHIRPUR', 'RANGPUR_SADAR', 'BADARGANJ', 'GANGACHARA', 'KAUNIA', 'MITHAPUKUR', 'PIRGACHHA', 'PIRGANJ', 'TARAGANJ', 'DINAJPUR_SADAR', 'BIRAMPUR', 'BIRGANJ', 'BIRAL', 'BOCHAGANJ', 'CHIRIRBANDAR', 'FULBARI', 'GHORAGHAT', 'HAKIMPUR', 'KAHAROLE', 'KHANSAMA', 'NAWABGANJ_DINAJPUR', 'PARBATIPUR', 'GAIBANDHA_SADAR', 'FULCHHARI', 'GABTALI_GAIBANDHA', 'GOBINDAGANJ', 'PALASHBARI', 'SADULLAPUR', 'SUNDARGANJ', 'KURIGRAM_SADAR', 'BHURUNGAMARI', 'CHAR_RAJIBPUR', 'CHILMARI', 'PHULBARI_KURIGRAM', 'NAGESHWARI', 'RAJARHAT', 'RAOMARI', 'ULIPUR', 'LALMONIRHAT_SADAR', 'ADITMARI', 'HATIBANDHA', 'KALIGANJ_LALMONIRHAT', 'PATGRAM', 'NILPHAMARI_SADAR', 'DIMLA', 'DOMAR', 'JALDHAKA', 'KISHOREGANJ_NILPHAMARI', 'SAIDPUR', 'PANCHAGARH_SADAR', 'ATWARI', 'BODA', 'DEBIGANJ', 'TETULIA', 'THAKURGAON_SADAR', 'BALIADANGI', 'HARIPUR', 'PIRGANJ_THAKURGAON', 'RANISANKAIL', 'MYMENSINGH_SADAR', 'BHALUKA', 'DHOBAURA', 'FULBARIA_MYMENSINGH', 'GAFFARGAON', 'GAURIPUR', 'HALUAGHAT', 'ISHWARGANJ', 'MUKTAGACHHA', 'NANDAIL', 'PHULPUR', 'TRISHAL', 'TARA_KHANDA', 'JAMALPUR_SADAR', 'BAKSIGANJ', 'DEWANGANJ', 'ISLAMPUR', 'MADARGANJ', 'MELANDAHA', 'SARISHABARI', 'NETROKONA_SADAR', 'ATPARA', 'BARHATTA', 'DURGAPUR_NETROKONA', 'KALMAKANDA', 'KENDUA', 'KHALIAJURI', 'MADAN', 'MOHANGANJ', 'PURBADHALA', 'SHERPUR_SADAR', 'JHENAIGATI', 'NAKLA', 'NALITABARI', 'SREEBARDI');

-- CreateEnum
CREATE TYPE "Gender" AS ENUM ('MALE', 'FEMALE');

-- DropForeignKey
ALTER TABLE "Post" DROP CONSTRAINT "Post_authorId_fkey";

-- DropTable
DROP TABLE "Post";

-- DropTable
DROP TABLE "User";

-- CreateTable
CREATE TABLE "Address" (
    "id" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "addressType" "AddressType" NOT NULL,
    "division" "Division" NOT NULL,
    "district" "District" NOT NULL,
    "upazila" "Upazila" NOT NULL,
    "street" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Address_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "emailVerified" BOOLEAN NOT NULL DEFAULT false,
    "image" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "user_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "session" (
    "id" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "token" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "userId" TEXT NOT NULL,

    CONSTRAINT "session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "account" (
    "id" TEXT NOT NULL,
    "accountId" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "accessToken" TEXT,
    "refreshToken" TEXT,
    "idToken" TEXT,
    "accessTokenExpiresAt" TIMESTAMP(3),
    "refreshTokenExpiresAt" TIMESTAMP(3),
    "scope" TEXT,
    "password" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "account_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "verification" (
    "id" TEXT NOT NULL,
    "identifier" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "verification_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "educations" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "institution" TEXT NOT NULL,
    "degree" TEXT NOT NULL,
    "fieldOfStudy" TEXT NOT NULL,
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3),
    "grade" TEXT,
    "description" TEXT,

    CONSTRAINT "educations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "StudentProfile" (
    "id" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "phoneNumber" TEXT NOT NULL,
    "whatsAppNumber" TEXT,
    "gender" "Gender",
    "dateOfBirth" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "StudentProfile_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Address_studentId_key" ON "Address"("studentId");

-- CreateIndex
CREATE UNIQUE INDEX "user_email_key" ON "user"("email");

-- CreateIndex
CREATE INDEX "session_userId_idx" ON "session"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "session_token_key" ON "session"("token");

-- CreateIndex
CREATE INDEX "account_userId_idx" ON "account"("userId");

-- CreateIndex
CREATE INDEX "verification_identifier_idx" ON "verification"("identifier");

-- CreateIndex
CREATE UNIQUE INDEX "StudentProfile_email_key" ON "StudentProfile"("email");

-- CreateIndex
CREATE UNIQUE INDEX "StudentProfile_studentId_key" ON "StudentProfile"("studentId");

-- CreateIndex
CREATE UNIQUE INDEX "StudentProfile_phoneNumber_key" ON "StudentProfile"("phoneNumber");

-- AddForeignKey
ALTER TABLE "Address" ADD CONSTRAINT "Address_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "StudentProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "session" ADD CONSTRAINT "session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "account" ADD CONSTRAINT "account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "educations" ADD CONSTRAINT "educations_userId_fkey" FOREIGN KEY ("userId") REFERENCES "StudentProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
